name: 'Bump Version'
on:
  push:
    branches:
      - 'foo'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-bump:
    name: 'Version Bump'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Update Version'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
          git fetch origin
          version_base=$(git show 'HEAD^:package/version')
          ./package/version.sh bump "${version_base}"
          ./package/version.sh sub
          git add --update
          if git commit --message "Set Version: $(cat package/version)"; then
            git push origin foo
          fi
